name: Check and Tag Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(python -c "import xml.etree.ElementTree as ET; \
                              tree = ET.parse('pom.xml'); \
                              root = tree.getroot(); \
                              ns = {'m': 'http://maven.apache.org/POM/4.0.0'}; \
                              version = root.find('m:version', ns).text; \
                              print(version)")
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Found version: $version"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check for existing tag
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create tag if it does not exist
        if: env.TAG_EXISTS == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
