name: Check and Tag Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Install the latest Temurin JDK
          java-version: '17'      # Specify the Java version you want to use

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(xmllint --xpath "string(//project/version)" pom.xml)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Found version: $version"

      - name: Check for existing tag
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "v${{ env.VERSION }}")
          if [ -z "$TAG_EXISTS" ]; then
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Create tag if it does not exist
        if: env.TAG_EXISTS == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
